### ISSUE TITLE
Save feature importance figures to mlflow

### ISSUE THREAD

**Issue by upura** [upura/ayniy#84]
https://github.com/mlflow/mlflow/pull/3728

**Comment by harupy** [comment]
You can use [`log_figure`](https://2604-136202695-gh.circle-artifacts.com/0/docs/build/html/python_api/mlflow.html#mlflow.log_figure) instead of `log_image` to log figures (matplotlib or plotly). This is a bit confusing but `log_image` logs an object that represents an image (e.g. numpy array).

```python
# matplotlib workflow

plt.figure(...)
...
mlflow.log_figure(plt.gcf(), "figure.png")

# or

fig, ax = plt.subplots()
...
mlflow.log_figure(fig, "figure.png")
```

**Comment by upura** [comment]
Oh, I didn't know that. Thanks for pointing out.
